server {
    listen 80;

    location /api/ {
        proxy_pass         http://beff:3001;
        proxy_http_version 1.1;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
    }

    location /auth/ {
        proxy_pass         http://beff:3001;
        proxy_http_version 1.1;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
    }

    location /health {
        proxy_pass         http://beff:3001;
        proxy_http_version 1.1;
    }

    location / {
        root       /usr/share/nginx/html;
        try_files  $uri $uri/ /index.html;
    }
}
